name: focabot
title: FocaBot
icon: src/icon.png
license: MIT
base: core18
version: '2.0+git'
summary: Discord Music Bot
description: |
  FocaBot is an open source music bot for Discord, it's easy to setup and comes
  with support for many video and audio streaming platforms, as well as some additional
  features like audio filters, video screenshots and livestream/radio support.

  Check the docs at https://www.focabot.xyz/
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
parts:
  focabot:
    plugin: nodejs
    build-packages:
      - git
      - python
      - build-essential
      - libtool
      - automake
    stage-packages:
      - python
    source: https://github.com/FocaBot/FocaBot.git
    source-branch: dev
    nodejs-version: '10.15.3'
    nodejs-package-manager: yarn
    override-build: |
      export PATH=$PATH:../npm/bin
      yarn run build
      # Peer dependencies for discord.js
      yarn add bufferutil@^3.0.3 \
        erlpack@github:discordapp/erlpack \
        node-opus@^0.2.7 \
        opusscript@^0.0.6 \
        sodium@^2.0.3 \
        libsodium-wrappers@^0.7.3 \
        uws@^9.14.0
      snapcraftctl build
apps:
  focabot:
    command: focabot
